import { ColumnImages } from "@/public/images";

export const articleList = [
  {
    id: 0,
    date: "2021.05.17",
    time: "23:25",
    image: ColumnImages.column1,
    title: "魚を食べて頭もカラダも元気に！知っておきたい魚を食べるメリ…",
    hashtags: ["#魚料理", "#和食", "#DHA"],
  },
  {
    id: 1,
    date: "2021.05.17",
    time: "23:25",
    image: ColumnImages.column2,
    title: "魚を食べて頭もカラダも元気に！知っておきたい魚を食べるメリ…",
    hashtags: ["#魚料理", "#和食", "#DHA"],
  },
  {
    id: 2,
    date: "2021.05.17",
    time: "23:25",
    image: ColumnImages.column3,
    title: "魚を食べて頭もカラダも元気に！知っておきたい魚を食べるメリ…",
    hashtags: ["#魚料理", "#和食", "#DHA"],
  },
  {
    id: 3,
    date: "2021.05.17",
    time: "23:25",
    image: ColumnImages.column4,
    title: "魚を食べて頭もカラダも元気に！知っておきたい魚を食べるメリ…",
    hashtags: ["#魚料理", "#和食", "#DHA"],
  },
  {
    id: 4,
    date: "2021.05.17",
    time: "23:25",
    image: ColumnImages.column5,
    title: "魚を食べて頭もカラダも元気に！知っておきたい魚を食べるメリ…",
    hashtags: ["#魚料理", "#和食", "#DHA"],
  },
  {
    id: 5,
    date: "2021.05.17",
    time: "23:25",
    image: ColumnImages.column6,
    title: "魚を食べて頭もカラダも元気に！知っておきたい魚を食べるメリ…",
    hashtags: ["#魚料理", "#和食", "#DHA"],
  },
  {
    id: 6,
    date: "2021.05.17",
    time: "23:25",
    image: ColumnImages.column7,
    title: "魚を食べて頭もカラダも元気に！知っておきたい魚を食べるメリ…",
    hashtags: ["#魚料理", "#和食", "#DHA"],
  },
  {
    id: 7,
    date: "2021.05.17",
    time: "23:25",
    image: ColumnImages.column8,
    title: "魚を食べて頭もカラダも元気に！知っておきたい魚を食べるメリ…",
    hashtags: ["#魚料理", "#和食", "#DHA"],
  },
];
